wiki/encyclopedia/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('new_page/', views.new_page, name='new_page'),
    path("randompage/", views.randompage, name="randompage"),
    path("test/", views.test, name="test"),
    path("search_results/", views.search_results, name="search_results"),
    path('edit/<str:title>/', views.edit_entry, name='edit_entry'),
    path("<str:title>", views.entry, name="entry")
    ]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django import forms
from django.shortcuts import render, redirect
from django.contrib import messages  # Import messages module for displaying messages
from . import util
from .util import fuck_generator
from markdown2 import Markdown
import random

#vars for converting md to html
markdowner = Markdown()

class NewPageForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    content = forms.CharField(label='Content', widget=forms.Textarea)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def new_page(request):
    if request.method == 'POST':
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            if util.get_entry(title):
                form.add_error('title', 'Idiot! Titlen eksisterer allerede - prøv igen...')
            else:
                util.save_entry(title, content)
                return redirect('entry', title=title)
    else:
        form = NewPageForm()
    return render(request, 'encyclopedia/new_page.html', {'form': form})

def randompage(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    return redirect('entry', title=random_entry)

def search_results(request):
    query = request.GET.get('q')
    if query:
        entries = util.list_entries()
        matching_entries = [entry for entry in entries if query.lower() in entry.lower()]
        if matching_entries:
            return render(request, "encyclopedia/search_results.html", {"query": query, "entries": matching_entries})
        else:
            return render(request, "encyclopedia/search_results.html", {"query": query, "entries": []})
    else:
        return render(request, "encyclopedia/index.html")

def entry(request, title):
    page = util.get_entry(title)
    if page:
        page_converted = markdowner.convert(page)
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "page": page_converted
        })
    else:
        return render(request, "encyclopedia/404.html")

def edit_entry(request, title):
    entry_content = util.get_entry(title)
    if entry_content:
        if request.method == 'POST':
            form = NewPageForm(request.POST)
            if form.is_valid():
                content = form.cleaned_data['content']
                util.save_entry(title, content)
                messages.success(request, f'Changes to "{title}" were saved successfully.')
                return redirect('entry', title=title)
        else:
            initial_data = {'content': entry_content}
            form = NewPageForm(initial=initial_data)
        return render(request, 'encyclopedia/edit_entry.html', {'form': form, 'title': title})
    else:
        return render(request, "encyclopedia/404.html")

def test(request):
    fucks = fuck_generator("can be anything. it just needs a string")
    return render(request, "encyclopedia/test.html", {'fucks': fucks})

wiki/encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry - {{ title }}
{% endblock %}

{% block body %}
<h2>Edit Entry: {{ title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
</form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %}

<div>
    {{ page|safe }}
</div>

<a href="{% url 'edit_entry' title=title %}">Edit Entry</a>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="GET" action="{% url 'search_results' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit" value="Search">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}
{% load static %}
        
        {% block title %}
        
        Create New Page
     
        {% endblock %}

    {% block body %}
    <h2>Create New Page</h2>
    <form method="post">
      {% csrf_token %}
      <div class="form-field {% if form.title.errors %}has-error{% endif %}">
        <label for="id_title">Title:</label>
        {{ form.title }}
        {% if form.title.errors %}
          <div class="error">{{ form.title.errors.0 }}</div>
        {% endif %}
      </div>
      <div class="form-field {% if form.content.errors %}has-error{% endif %}">
        <label for="id_content">Content:</label>
        {{ form.content }}
        {% if form.content.errors %}
          <div class="error">{{ form.content.errors.0 }}</div>
        {% endif %}
      </div>
      <button type="submit">Save</button>
    </form>
    {% endblock %}
</body>
</html>

wiki/encyclopedia/templates/encyclopedia/no_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results - {{ query }}
{% endblock %}

{% block body %}
    <h1>Search Results for "{{ query }}"</h1>
    <p>There where no search results matching  {{ query }}</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results - {{ query }}
{% endblock %}

{% block body %}
    <h1>Search Results for "{{ query }}"</h1>
    {% if entries %}
        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'entry' title=entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No matching entries found for "{{ query }}".</p>
        <a href="{% url 'index' %}">Go Back</a>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/test.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>This is

    {% for fuck in fucks %}
    {{ fuck }}
    {% endfor %}

a TEST</h1>


{% endblock %}